//! DATA
const DATA = [
  {
    id: 0,
    url: "./assests/img/the-shawshank-redemption.jpg",
    wide: "./assests/img/the-shawshank-redemption-h.jpg",
    movie_name: "The Shawshank Redemption",
    release_date: "1994-09-23",
    rating: 5,
    cast: ["Tim Robbins", "Morgan Freeman", "Bob Gunton"],
    description:
      "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
  },
  {
    id: 1,
    url: "./assests/img/The-Dark-Knight.jpg",
    wide: "./assests/img/The-Dark-Knight-wide.jpg",
    movie_name: "The Dark Knight",
    release_date: "2008-07-18",
    rating: 4,
    cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart"],
    description:
      "When the menace known as the Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham.",
  },
  {
    id: 2,
    url: "./assests/img/Inception.jpg",
    wide: "./assests/img/Inception-wide.avif",
    movie_name: "Inception",
    release_date: "2010-07-16",
    rating: 5,
    cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt", "Elliot Page"],
    description:
      "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a CEO.",
  },
  {
    id: 3,
    url: "./assests/img/The-Matrix.jpg",
    wide: "./assests/img/The-Matrix-wide.jpg",
    movie_name: "The Matrix",
    release_date: "1999-03-31",
    rating: 5,
    cast: ["Keanu Reeves", "Laurence Fishburne", "Carrie-Anne Moss"],
    description:
      "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
  },
  {
    id: 4,
    url: "./assests/img/Interstellar.png",
    wide: "./assests/img/Interstellar-wide.png",
    movie_name: "Interstellar",
    release_date: "2014-11-07",
    rating: 5,
    cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
    description:
      "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
  },
  {
    id: 5,
    url: "./assests/img/Iron-Man.jpg",
    wide: "./assests/img/Iron-Man-wide.webp",
    movie_name: "Iron Man",
    release_date: "2008-05-02",
    rating: 5,
    cast: ["Robert Downey Jr.", "Gwyneth Paltrow", "Jeff Bridges"],
    description:
      "After being held captive in an Afghan cave, billionaire engineer Tony Stark creates a unique weaponized suit of armor to fight evil.",
  },
  {
    id: 6,
    url: "./assests/img/Speed.jpg",
    wide: "./assests/img/Speed-wide.webp",
    movie_name: "Speed",
    release_date: "1994-06-10",
    rating: 4,
    cast: ["Keanu Reeves", "Sandra Bullock", "Dennis Hopper"],
    description:
      "A young police officer must prevent a bomb from exploding aboard a city bus by keeping its speed above 50 mph.",
  },
  {
    id: 7,
    url: "./assests/img/The-Godfather.jpg",
    wide: "./assests/img/The-Godfather-wide.jpg",
    movie_name: "The Godfather",
    release_date: "1972-03-24",
    rating: 5,
    cast: ["Marlon Brando", "Al Pacino", "James Caan"],
    description:
      "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
  },
  {
    id: 8,
    url: "./assests/img/Iron-Man-2.jpg",
    wide: "./assests/img/Iron-Man-2-wide.webp",
    movie_name: "Iron Man 2",
    release_date: "2010-05-07",
    rating: 5,
    cast: ["Robert Downey Jr.", "Gwyneth Paltrow", "Don Cheadle"],
    description:
      "Tony Stark faces pressure from various sources to share his technology while facing a powerful new enemy.",
  },
  {
    id: 9,
    url: "./assests/img/Fight-Club.jpg",
    wide: "./assests/img/Fight-Club-wide.avif",
    movie_name: "Fight Club",
    release_date: "1999-10-15",
    rating: 5,
    cast: ["Brad Pitt", "Edward Norton", "Helena Bonham Carter"],
    description:
      "An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.",
  },
  {
    id: 10,
    url: "./assests/img/kraven-the-hunter.jpg",
    wide: "./assests/img/kraven-the-hunter-wide.jpg",
    movie_name: "Kraven The Hunter",
    release_date: "2023-09-22",
    rating: 4,
    cast: ["Aaron Taylor-Johnson", "Ariana DeBose", "Russell Crowe"],
    description:
      "Kraven embarks on a journey to hunt dangerous poachers and criminals as an anti-hero in the Marvel Universe.",
  },
  {
    id: 11,
    url: "./assests/img/Venom-Let-There-Be-Carnage.jpg",
    wide: "./assests/img/Venom-Let-There-Be-Carnage-wide.jpg",
    movie_name: "Venom: Let There Be Carnage",
    release_date: "2021-10-01",
    rating: 3,
    cast: ["Tom Hardy", "Woody Harrelson", "Michelle Williams"],
    description:
      "Eddie Brock's symbiotic relationship is tested as he faces off against Carnage, a menacing new foe.",
  },
  {
    id: 12,
    url: "./assests/img/Venom.jpg",
    wide: "./assests/img/Venom-wide.webp",
    movie_name: "Venom",
    release_date: "2018-10-05",
    rating: 4,
    cast: ["Tom Hardy", "Michelle Williams", "Riz Ahmed"],
    description:
      "A failed journalist becomes the host of an alien symbiote, which grants him superhuman abilities.",
  },
  {
    id: 13,
    url: "./assests/img/avatar.jpg",
    wide: "./assests/img/avatar-wide.jpg",
    movie_name: "Avatar",
    release_date: "2009-12-18",
    rating: 5,
    cast: ["Sam Worthington", "Zoe Saldana", "Sigourney Weaver"],
    description:
      "A paraplegic Marine is sent to the moon Pandora on a unique mission but becomes torn between following orders and protecting the world he feels is his home.",
  },
  {
    id: 14,
    url: "./assests/img/the-avengers.jpg",
    wide: "./assests/img/the-avengers-wide.webp",
    movie_name: "The Avengers",
    release_date: "2012-05-04",
    rating: 5,
    cast: ["Robert Downey Jr.", "Chris Evans", "Scarlett Johansson"],
    description:
      "Earth's mightiest heroes must come together to stop an alien invasion led by Loki.",
  },
  {
    id: 15,
    url: "./assests/img/guardians-of-the-galaxy.jpg",
    wide: "./assests/img/guardians-of-the-galaxy-wide.webp",
    movie_name: "Guardians of the Galaxy",
    release_date: "2014-08-01",
    rating: 5,
    cast: ["Chris Pratt", "Zoe Saldana", "Dave Bautista"],
    description:
      "A group of intergalactic criminals must pull together to stop a fanatical warrior with plans to purge the universe.",
  },
  {
    id: 16,
    url: "./assests/img/jurassic-park.jpg",
    wide: "./assests/img/jurassic-park-wide.jpg",
    movie_name: "Jurassic Park",
    release_date: "1993-06-11",
    rating: 5,
    cast: ["Sam Neill", "Laura Dern", "Jeff Goldblum"],
    description:
      "A pragmatic paleontologist visiting an almost complete theme park is tasked with protecting a couple of kids after a power failure causes the park's cloned dinosaurs to run loose.",
  },
  {
    id: 17,
    url: "./assests/img/star-wars.jpeg",
    wide: "./assests/img/star-wars-wide.webp",
    movie_name: "Star Wars: A New Hope",
    release_date: "1977-05-25",
    rating: 5,
    cast: ["Mark Hamill", "Harrison Ford", "Carrie Fisher"],
    description:
      "Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee, and two droids to save the galaxy from the Empire's world-destroying battle station.",
  },
  {
    id: 18,
    url: "./assests/img/spider-man-no-way-home.jpg",
    wide: "./assests/img/spider-man-no-way-home-wide.webp",
    movie_name: "Spider-Man: No Way Home",
    release_date: "2021-12-17",
    rating: 5,
    cast: ["Tom Holland", "Zendaya", "Benedict Cumberbatch"],
    description:
      "Peter Parker seeks Doctor Strange's help to make his identity as Spider-Man a secret again, leading to a spell gone wrong.",
  },
  {
    id: 19,
    url: "./assests/img/terminator.jpg",
    wide: "./assests/img/terminator-wide.jpg",
    movie_name: "The Terminator",
    release_date: "1984-10-26",
    rating: 5,
    cast: ["Arnold Schwarzenegger", "Linda Hamilton", "Michael Biehn"],
    description:
      "A cyborg is sent from the future on a deadly mission, and only a young woman and a soldier can stop it.",
  },
  {
    id: 20,
    url: "./assests/img/mad-max-fury-road.jpg",
    wide: "./assests/img/mad-max-fury-road-wide.jpg",
    movie_name: "Mad Max: Fury Road",
    release_date: "2015-05-15",
    rating: 5,
    cast: ["Tom Hardy", "Charlize Theron", "Nicholas Hoult"],
    description:
      "In a post-apocalyptic wasteland, Max teams up with Furiosa to flee a tyrant and find a safe haven.",
  },
  {
    id: 21,
    url: "./assests/img/black-panther.jpg",
    wide: "./assests/img/black-panther-wide.avif",
    movie_name: "Black Panther",
    release_date: "2018-02-16",
    rating: 5,
    cast: ["Chadwick Boseman", "Michael B. Jordan", "Lupita Nyong'o"],
    description:
      "T'Challa, heir to the hidden kingdom of Wakanda, must step forward to lead his people and face a dangerous adversary.",
  },
  {
    id: 22,
    url: "./assests/img/the-hunger-games.jpg",
    wide: "./assests/img/the-hunger-games-wide.jpg",
    movie_name: "The Hunger Games",
    release_date: "2012-03-23",
    rating: 4,
    cast: ["Jennifer Lawrence", "Josh Hutcherson", "Liam Hemsworth"],
    description:
      "In a dystopian future, Katniss Everdeen volunteers to take her sister's place in a deadly televised competition.",
  },
  {
    id: 23,
    url: "./assests/img/transformers.jpg",
    wide: "./assests/img/transformers-wide.webp",
    movie_name: "Transformers",
    release_date: "2007-07-03",
    rating: 4,
    cast: ["Shia LaBeouf", "Megan Fox", "Josh Duhamel"],
    description:
      "An ancient struggle between two Cybertronian races comes to Earth, where humanity's fate hangs in the balance.",
  },
  {
    id: 24,
    url: "./assests/img/x-men.jpg",
    wide: "./assests/img/x-men-wide.webp",
    movie_name: "X-Men",
    release_date: "2000-07-14",
    rating: 4,
    cast: ["Hugh Jackman", "Patrick Stewart", "Ian McKellen"],
    description:
      "Two mutants must come together to prevent a war between mutants and humans.",
  },
  {
    id: 25,
    url: "./assests/img/doctor-strange.jpg",
    wide: "./assests/img/doctor-strange-wide.jpg",
    movie_name: "Doctor Strange",
    release_date: "2016-11-04",
    rating: 5,
    cast: ["Benedict Cumberbatch", "Tilda Swinton", "Rachel McAdams"],
    description:
      "A neurosurgeon seeks to heal his hands and ends up in a mystic world beyond imagination.",
  },
  {
    id: 26,
    url: "./assests/img/star-trek.jpg",
    wide: "./assests/img/star-trek-wide.avif",
    movie_name: "Star Trek",
    release_date: "2009-05-08",
    rating: 5,
    cast: ["Chris Pine", "Zachary Quinto", "Zoe Saldana"],
    description:
      "A young crew embarks on their first mission, battling a Romulan who threatens their planet.",
  },
  {
    id: 27,
    url: "./assests/img/edge-of-tomorrow.jpg",
    wide: "./assests/img/edge-of-tomorrow-wide.avif",
    movie_name: "Edge of Tomorrow",
    release_date: "2014-06-06",
    rating: 5,
    cast: ["Tom Cruise", "Emily Blunt", "Bill Paxton"],
    description:
      "A soldier fighting aliens gets caught in a time loop, reliving his last day over and over.",
  },
  {
    id: 28,
    url: "./assests/img/pacific-rim.jpg",
    wide: "./assests/img/pacific-rim-wide.jpg",
    movie_name: "Pacific Rim",
    release_date: "2013-07-12",
    rating: 4,
    cast: ["Charlie Hunnam", "Idris Elba", "Rinko Kikuchi"],
    description:
      "As monstrous creatures threaten Earth, humanity's last hope is giant robots piloted by soldiers.",
  },
  {
    id: 29,
    url: "./assests/img/indiana-jones.jpg",
    wide: "./assests/img/indiana-jones-wide.jpg",
    movie_name: "Indiana Jones and the Last Crusade",
    release_date: "1989-05-24",
    rating: 5,
    cast: ["Harrison Ford", "Sean Connery", "Denholm Elliott"],
    description:
      "Archaeologist Indiana Jones teams up with his father to find the Holy Grail and thwart the Nazis.",
  },
];

const favDATA = JSON.parse(localStorage.getItem("favoriteMovies")) || [];
